### PR TITLE
Various 0.2/latest updates

### PR DESCRIPTION
**Pull request by joshmoore**
* [x] migrate 0.2 to latest
* [x] add bdv-ome-zarr
* [x] add reviewing links to README
* [ ] ~produce a linked table of implementations~

### CODE REVIEW

**Comment by joshmoore** [comment]
The diff between 0.2/index.bs and latest with this PR:

```
(base) /opt/ngff $diff 0.2/index.bs latest/index.bs
5c5,6
< Status: w3c/CG-FINAL
---
> Status: LS-COMMIT
> Status: w3c/ED
7c8
< URL: https://ngff.openmicroscopy.org/0.2/
---
> URL: https://ngff.openmicroscopy.org/latest/
20,21c21,23
< Status Text: This is the 0.2 release of this specification. Migration scripts
< Status Text: will be provided between numbered versions. Data written with the latest version
---
> Status Text: The current released version of this specification is
> Status Text: <a href="../0.2/index.html">0.2</a>. Migration scripts
> Status Text: will be provided between numbered versions. Data written with these latest changes
25d26
<
273c274
< "version": "0.2",                     # Current version
---
> "version": "0.1",                     # Current version
350c351
<     "version": "0.2",
---
>     "version": "0.1",
462c463
<     "version": "0.2",
---
>     "version": "0.1",
529c530
<     "version": "0.2"
---
>     "version": "0.1"
572c573
< [Next-generation file format (NGFF) specifications for storing bioimaging data in the cloud.](https://ngff.openmicroscopy.org/0.2)
---
> [Next-generation file format (NGFF) specifications for storing bioimaging data in the cloud.](https://ngff.openmicroscopy.org/0.1)
574c575
< This edition of the specification is [https://ngff.openmicroscopy.org/0.2/](https://ngff.openmicroscopy.org/0.2/]).
---
> This edition of the specification is [https://ngff.openmicroscopy.org/0.1/](https://ngff.openmicroscopy.org/0.1/]).
```

Moving forward, I'd suggest all changes go to `latest` and that we write a script for backporting (unless someone has a better idea)

**Comment by will-moore** [comment]
Looks good.
I seem to remember that nested chunks requires certain minimal versions of `zarr` that recognise `dimension_separator`?
Do we want to mention that at all, or is that beyond the scope of this spec?

**Comment by joshmoore** [comment]
@tischi: https://ngff.openmicroscopy.org/latest/#implementations is updated here. I don't know if we want to add the table just yet. At the moment, it would just all say, "Yes". If by the time you guys are ready to release v0.3 there are clear "No"s, then feel free to add.

**Comment by joshmoore** [comment]
> Do we want to mention that at all, or is that beyond the scope of this spec?

That probably needs to live in ome-zarr-py (which would then influence omero-cli-zarr, etc.)

**Comment by joshmoore** [comment]
fixed the old 0.1 references thanks to @sbesson. new diff is:

```patch
(base) /opt/ngff $diff 0.2/index.bs latest/index.bs
5c5,6
< Status: w3c/CG-FINAL
---
> Status: LS-COMMIT
> Status: w3c/ED
7c8
< URL: https://ngff.openmicroscopy.org/0.2/
---
> URL: https://ngff.openmicroscopy.org/latest/
20,21c21,23
< Status Text: This is the 0.2 release of this specification. Migration scripts
< Status Text: will be provided between numbered versions. Data written with the latest version
---
> Status Text: The current released version of this specification is
> Status Text: <a href="../0.2/index.html">0.2</a>. Migration scripts
> Status Text: will be provided between numbered versions. Data written with these latest changes
```

**Review by sbesson — APPROVED** [review]

**Comment by sbesson** [comment]
Now published at https://ngff.openmicroscopy.org/latest/

**Comment by joshmoore** [comment]
Ta.

**Pull request merged**
