### PR TITLE
Proposal: move to RTD

### PR DESCRIPTION
**Pull request by joshmoore**
This branch contains the necessary bootstrapping to deploy the specifications as well as other sphinx pages on https://readthedocs.org:

 * [x] `conf.py` runs bikeshed which is copied via `html_extra_path`
 * [x] `index.rst` redirects to latest/index.html as before
 * [x] `about/index.md` is available as a new top-level landing page

This was largely done in order to provide the ngff.openmicroscopy.org/tools and ngff.openmicroscopy.org/data URLs as decided in the[OME-Zarr preprint](https://www.biorxiv.org/content/10.1101/2023.02.17.528834v2):

 * [x] `tools/index.rst` is largely done and driven by `lists.csv` (but could look nicer)
 * [x] `data/index.md` is a simple but linked table at the moment
 * [ ] `publications/index.md` has been added but is still unpopulated

The current branch can be reviewed at https://ngff.readthedocs.io/en/rtd/about/index.html . Once this PR is merged, https://ngff.readthedocs.io/en/latest/about/index.html would become a new default landing location without further configuration and the URLs needed can redirect to, e.g., https://ngff.readthedocs.io/en/latest/tools/

We should likely consider renaming the sphinx-specific `latest` to not conflict with the spec-specific `latest`, otherwise we get a default URL of https://ngff.readthedocs.io/en/latest/latest/index.html . If there's a general consensus, we could also redirect `https://ngff.openmicroscopy.org` away from GitHub pages and to `https://ngff.readthedocs.io`. Additionally, we can drop the redirect to `latest/index.html` in favor of a top-level landing page like `about/index.md`.

TODOS:
 - [x] Tools: Move tools table to [long-form markdown](https://hackmd.io/2JqekrBXSiOCdj3nRsOLIw)
 - [x] Data: Fix DANDI URL parsing
 - [x] Data: Combine names with URL, add description column
 - [x] Publish schemas (see [example](https://github.com/ome/ngff/blob/15565cb8301e14fc9ba2fc63b6332a97534cee67/0.4/schemas/ome.schema#L3))
 - [ ] Redirect DNS
 - [ ] Create issue for collecting logos (cf. https://zarr.dev/adopters/)

### CODE REVIEW

**Comment by will-moore** [comment]
Looks nice! 👍

**Comment by bogovicj** [comment]
Is it right that this could help divide "strictly spec" from "spec-adjacent" (e.g. examples) to different pages? Hopefully resulting in a less cluttered spec?

**Comment by joshmoore** [comment]
From my POV, that's certainly an option, sure. An additional next step that could go in the description of this PR but I didn't really want to get in is that we could drop bikeshed in favor of some flavor of plain markdown. That might make it easier to refactor more readily in this repo.

**Comment by joshmoore** [comment]
Ok, I think that includes all the "must-fix" items. Biggest question remaining in my mind is whether or not to set the `Single version` flag:

> A single version site has no translations and only your "latest" version, served at the root of the domain. Use this with caution, only turn it on if you will never have multiple versions of your docs.

If we do that, then once DNS is re-directed, all previous URLs should continue working.

**Comment by joshmoore** [comment]
Discussing during the "Zarr Resources" call with @will-moore and @pwalczysko, we're going to merge this and drop the `en/latest` from the URL in order to prepare for DNS migration.

**Comment by joshmoore** [comment]
@ome/ngff: https://ngff.openmicroscopy.org/data/ is now live with a DNS entry to readthedocs.io

**Pull request merged**
