### PR TITLE
remove "windows" and "color" from omero metadata as required

### PR DESCRIPTION
**Pull request by giovp**
ref #192 . I left the "windows" parameters as "required" but I'm not sure if it makes sense.

### CODE REVIEW

**Review by will-moore — APPROVED** [review]
Spec change looks good to me.
I don't see that this relaxation needs any changes to the tests

**Comment by will-moore** [comment]
I think the failing test above is due to the trailing comma on the previous line that needs to be removed

**Comment by giovp** [comment]
bump

**Comment by will-moore** [comment]
Thanks!

**Pull request merged**
