### PR TITLE
improve description of omero metadata

### PR DESCRIPTION
**Pull request by giovp**
Currently, the omero metadata section in the specs could be a bit more descriptive, this is a small attempt.

This info was kindly summarized by @will-moore here: https://github.com/ome/ome-zarr-py/pull/261#issuecomment-1525658925

EDIT: while this PR is purely to improve documentation, might be related to potential relaxation of omero metadata as discussed in https://github.com/ome/ngff/issues/192

### CODE REVIEW

**Comment by joshmoore** [comment]
Thanks, @giovp! (https://ngff--191.org.readthedocs.build/latest/index.html#omero-md)

If no one else has any comments, I'll move to get this in.

**Comment by will-moore** [comment]
Looks good.

Although we normally wouldn't make changes to a spec after release, this extra info *could* be added back to the `v0.4` spec and might be useful?

But not a blocker!

**Comment by will-moore** [comment]
Also with https://github.com/ome/ngff/issues/192 proposed, this change in latest would be updated again before release, so it would be good to have this description in the v0.4 spec, where it won't change.

**Comment by giovp** [comment]
sorry for radio silence @will-moore @joshmoore , I have time now, shall I just add the info as optional as discussed in #192 ? I yes, I can then submit changes to IO in `ome-zarr-py` . Let me know!

**Comment by will-moore** [comment]
I would copy what you have now to the v0.4 spec - since it describes that spec and is worth having there. Then (probably in #192) update it in the in `latest/index.bs` according to the proposed changes there. 
Probably easiest to keep them as separate PRs since this one just documents current state, but #192 is a change. I don't expect that to take a whole lot longer but you never know!

**Comment by giovp** [comment]
done, added it to 0.4

**Comment by will-moore** [comment]
Great, thanks!

**Pull request merged**
